// Generated by CoffeeScript 1.3.3
(function() {
  var Item, app, crypto, db, express, flash, http, nib, path, stylus;

  express = require('express');

  crypto = require('crypto');

  flash = require('connect-flash');

  path = require('path');

  http = require('http');

  stylus = require('stylus');

  nib = require('nib');

  db = require('mongoose');

  db.connect(process.env.MONGOHQ_URL);

  Item = db.model('Item', {
    text: String,
    category: String
  });

  app = express();

  app.configure(function() {
    app.set("port", process.env.PORT || 3000);
    app.set("views", __dirname + "/views");
    app.set("view engine", "jade");
    app.use(express.cookieParser('keyboard cat'));
    app.use(express.session({
      key: 'bing',
      cookie: {
        maxAge: 60000
      }
    }));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(flash());
    app.use(app.router);
    app.use(stylus.middleware({
      src: __dirname + '/assets',
      compile: function(str, path) {
        return stylus(str).set('filename', path).set('compress', true).use(nib());
      }
    }));
    return app.use(express["static"](path.join(__dirname, "assets")));
  });

  app.configure('development', function() {
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.configure('production', function() {
    return app.use(express.errorHandler());
  });

  app.get('/', function(req, res) {
    return res.render('index');
  });

  app.post('/add', function(req, res) {
    var newItem;
    newItem = new Item({
      text: req.body.text,
      category: req.body.category
    });
    return newItem.save(function(err) {
      if (err) {
        return res.send({
          saved: false
        });
      } else {
        return res.send({
          saved: true
        });
      }
    });
  });

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

}).call(this);
